/**
 * src/config/Themes.js
 * Centralized Design System for "Dawn of the New Morning"
 */

export const themes = {
  maritime: {
    id: 'maritime',
    name: 'Maritime',
    type: 'light',
    description: 'Ocean-inspired professional theme',
    colors: {
      primary: 'blue-600',
      secondary: 'slate-800',
      accent: 'emerald-500',
      background: 'slate-50',
      surface: 'white',
      text: 'slate-900',
      textMuted: 'slate-600',
      nameColor: 'blue-800',
      descriptionColor: 'teal-600',
      border: 'slate-200',
      success: 'emerald-500',
      warning: 'amber-500',
      error: 'red-600',
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark Mode',
    type: 'dark',
    description: 'High-contrast dark theme',
    colors: {
      primary: 'indigo-500',
      secondary: 'slate-900',
      accent: 'cyan-400',
      background: 'slate-950',
      surface: 'slate-900',
      text: 'slate-50',
      textMuted: 'slate-400',
      nameColor: 'indigo-300',
      descriptionColor: 'cyan-300',
      border: 'slate-700',
      success: 'emerald-400',
      warning: 'amber-400',
      error: 'red-500',
    },
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    type: 'light',
    description: 'Clean, minimalist aesthetic',
    colors: {
      primary: 'gray-900',
      secondary: 'gray-400',
      accent: 'amber-500',
      background: 'white',
      surface: 'gray-50',
      text: 'gray-900',
      textMuted: 'gray-600',
      nameColor: 'slate-900',
      descriptionColor: 'amber-700',
      border: 'gray-200',
      success: 'green-600',
      warning: 'amber-600',
      error: 'red-700',
    },
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    type: 'light',
    description: 'Warm, energetic theme',
    colors: {
      primary: 'orange-500',
      secondary: 'rose-600',
      accent: 'yellow-400',
      background: 'orange-50',
      surface: 'white',
      text: 'orange-950',
      textMuted: 'orange-700',
      nameColor: 'rose-700',
      descriptionColor: 'yellow-600',
      border: 'orange-200',
      success: 'green-500',
      warning: 'amber-500',
      error: 'red-600',
    },
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    type: 'light',
    description: 'Nature-inspired calm theme',
    colors: {
      primary: 'emerald-600',
      secondary: 'teal-700',
      accent: 'lime-400',
      background: 'emerald-50',
      surface: 'white',
      text: 'emerald-950',
      textMuted: 'emerald-700',
      nameColor: 'teal-800',
      descriptionColor: 'lime-600',
      border: 'emerald-200',
      success: 'emerald-500',
      warning: 'amber-500',
      error: 'red-600',
    },
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    type: 'dark',
    description: 'Neon-futuristic high-tech theme',
    colors: {
      primary: 'violet-900',
      secondary: 'fuchsia-900',
      accent: 'yellow-300',
      background: 'violet-950',
      surface: 'slate-900',
      text: 'yellow-300',
      textMuted: 'emerald-500',
      nameColor: 'fuchsia-300',
      descriptionColor: 'amber-600',
      border: 'violet-600',
      success: 'lime-400',
      warning: 'yellow-300',
      error: 'red-500',
    },
  },
  retro: {
    id: 'retro',
    name: 'Retro',
    type: 'light',
    description: 'Vintage 70s-inspired theme',
    colors: {
      primary: 'amber-700',
      secondary: 'orange-600',
      accent: 'yellow-400',
      background: 'yellow-50',
      surface: 'amber-100',
      text: 'amber-950',
      textMuted: 'orange-800',
      nameColor: 'red-600',
      descriptionColor: 'pink-600',
      border: 'orange-300',
      success: 'green-600',
      warning: 'orange-600',
      error: 'red-700',
    },
  },
  businessJet: {
    id: 'businessJet',
    name: 'Business Jet',
    type: 'light',
    description: 'Premium corporate luxury theme',
    colors: {
      primary: 'slate-900',
      secondary: 'amber-700',
      accent: 'blue-600',
      background: 'indigo-200',
      surface: 'stone-200',
      text: 'rose-700',
      textMuted: 'slate-900',
      nameColor: 'blue-700',
      descriptionColor: 'amber-600',
      border: 'slate-300',
      success: 'emerald-600',
      warning: 'amber-600',
      error: 'red-600',
    },
  },
};

export const getTheme = (themeId) => themes[themeId] || themes.maritime;