/**

 * Integrated with Gemini 2.0 Flash for Rapid Prototyping
 */

// Global Standard for every new page generated by the AI
export const WF3_PAGE_STANDARD = `
EVERY NEW PAGE MUST FOLLOW THIS ARCHITECTURAL STANDARD:
1. Frontmatter (title, sidebar_position).
2. :::info [ROLE | DURATION | COMPLEXITY] :::
3. ARCHITECTURE: A brief explanation of the logic or a Mermaid diagram.
4. STEPS: Clear, numbered instructions using the Triple-Level approach (Senior/Junior/Customer).
5. :::tip [CLIENT COMMUNICATION] How to explain this feature to a non-technical stakeholder. :::
6. AI-QUERIES: 3 example prompts the user can ask the AI about this specific page.
`;

/**
 * Calls the Gemini API with a system instruction and user prompt.
 * @param {string} apiKey - Your Gemini API key from Docusaurus customFields.
 * @param {string} prompt - The user's specific request.
 * @param {string} systemInstruction - The persona and project context (CODE_MAP).
 */
export async function callGeminiAPI(apiKey, prompt, systemInstruction) {
  // 1. Validate API Key Presence
  if (!apiKey) {
    throw new Error("MISSING_API_KEY: Gemini API Key is not defined in siteConfig.customFields.");
  }

  // Using Gemini 2.0 Flash for high-speed orchestration
  const url = `https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash:generateContent?key=${apiKey}`;
  
  const body = {
    contents: [{ 
      parts: [{ text: `SYSTEM INSTRUCTION:\n${systemInstruction}\n\nUSER REQUEST: ${prompt}` }] 
    }],
    generationConfig: {
      temperature: 0.7, // Balanced for creative orchestration and technical accuracy
      maxOutputTokens: 8192, // Maxed for Gemini 2.0 Flash to support full-page code gen
    }
  };

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });

    // 2. Comprehensive Status Code Handling
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      const message = errorData.error?.message || "Unknown API Error";

      switch (response.status) {
        case 401:
          throw new Error(`AUTHENTICATION_ERROR: Invalid API Key. (${message})`);
        case 403:
          throw new Error(`PERMISSION_DENIED: The API key does not have access to Gemini 2.0 Flash. (${message})`);
        case 429:
          throw new Error("QUOTA_EXCEEDED: The AI engine is cooling down (Rate Limit). Please wait 60 seconds.");
        case 500:
          throw new Error("SERVER_ERROR: Google's AI servers are currently struggling. Try again in a moment.");
        default:
          throw new Error(`API_RESPONSE_ERROR (${response.status}): ${message}`);
      }
    }

    const data = await response.json();
    
    // 3. Structural Validation of response
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error("ORCHESTRATION_FAILED: No response candidates returned. This might be due to safety filters.");
    }

    const responseText = data.candidates[0].content?.parts?.[0]?.text;

    if (!responseText) {
      throw new Error("EMPTY_RESPONSE: The AI returned a result but no text content was found.");
    }

    return responseText;
    
  } catch (error) {
    // Log for the developer, but re-throw for the UI to catch
    console.error("AI Service Orchestration Error:", error);
    throw error;
  }
}