/**
 * Dawn of the New Morning - Centralized AI Orchestration Service
 * Integrated with Gemini 2.0 Flash for Rapid Prototyping
 */

// Global Standard for every new page generated by the AI
export const WF3_PAGE_STANDARD = `
EVERY NEW PAGE MUST FOLLOW THIS ARCHITECTURAL STANDARD:
1. Frontmatter (title, sidebar_position).
2. :::info [ROLE | DURATION | COMPLEXITY] :::
3. ARCHITECTURE: A brief explanation of the logic or a Mermaid diagram.
4. STEPS: Clear, numbered instructions using the Triple-Level approach (Senior/Junior/Customer).
5. :::tip [CLIENT COMMUNICATION] How to explain this feature to a non-technical stakeholder. :::
6. AI-QUERIES: 3 example prompts the user can ask the AI about this specific page.
`;

/**
 * Calls the Gemini API with a system instruction and user prompt.
 * @param {string} apiKey - Your Gemini API key from Docusaurus customFields.
 * @param {string} prompt - The user's specific request.
 * @param {string} systemInstruction - The persona and project context (CODE_MAP).
 */
export async function callGeminiAPI(apiKey, prompt, systemInstruction) {
  // Using Gemini 2.0 Flash for high-speed orchestration
  const url = `https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash:generateContent?key=${apiKey}`;
  
  const body = {
    contents: [{ 
      parts: [{ text: `SYSTEM INSTRUCTION:\n${systemInstruction}\n\nUSER REQUEST: ${prompt}` }] 
    }],
    generationConfig: {
      temperature: 0.7, // Balanced for creative orchestration and technical accuracy
      maxOutputTokens: 4096, // Increased to allow full page generation
    }
  };

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });

    // Handle Quota limits (429 Too Many Requests)
    if (response.status === 429) {
      throw new Error("QUOTA EXCEEDED: The AI engine is cooling down. Please wait 60 seconds and try again.");
    }

    const data = await response.json();
    
    if (data.error) {
      throw new Error(`API ERROR: ${data.error.message}`);
    }

    if (!data.candidates || data.candidates.length === 0) {
      throw new Error("ORCHESTRATION FAILED: No response candidates returned from the engine.");
    }

    return data.candidates[0].content.parts[0].text;
    
  } catch (error) {
    console.error("AI Service Error:", error);
    throw error;
  }
}